
package VISTAS;

import MODELO.paciente;
import MODELO.pacienteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Darileysi Morales
 */
public class ActualizarPacientes extends javax.swing.JInternalFrame {

    pacienteDAO dao = new pacienteDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    int id_paciente;
    /**
     * Creates new form ActualizarPacientes
     */
    public ActualizarPacientes() {
        initComponents();
        listar();
    }
    
    // Rellenar tabla con los datos registrados
void listar() {
    List<paciente> lista = dao.listar();
    modelo = (DefaultTableModel) tablaPaciente.getModel();
    modelo.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
    
    Object[] ob = new Object[7];
    
    for (int i = 0; i < lista.size(); i++) {
        ob[0] = lista.get(i).getId_paciente();
        ob[1] = lista.get(i).getNombre();
        ob[2] = lista.get(i).getFecha_nacimiento();
        ob[3] = lista.get(i).getGenero();
        ob[4] = lista.get(i).getDomicilio();
        ob[5] = lista.get(i).getTelefono();
        ob[6] = lista.get(i).getContacto_emergencia();
        modelo.addRow(ob);
    }
    
    tablaPaciente.setModel(modelo);
    System.out.println("Listado de pacientes completado.");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        rdbMasculino = new javax.swing.JRadioButton();
        rdbFemenino = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtFechaN = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPaciente = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtContacto = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Actualizar registro de pacientes");

        jPanel1.setBackground(new java.awt.Color(195, 223, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE CONTROL DE PACIENTES CON DIABETES");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("ACTUALIZAR DATOS DE PACIENTES");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Gobierno de Mexico.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Secretaria de salud.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/INSABI.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/GUERRERO.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Transformando GUERRERO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(93, 93, 93)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(105, 105, 105)
                .addComponent(jLabel6)
                .addGap(97, 97, 97)
                .addComponent(jLabel7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 130));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setText("NOMBRE COMPLETO DEL PACIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtNombre.setBackground(new java.awt.Color(204, 204, 255));
        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 316, 24));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("GENERO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        rdbMasculino.setBackground(new java.awt.Color(195, 223, 234));
        buttonGroup1.add(rdbMasculino);
        rdbMasculino.setText("Masculino");
        jPanel1.add(rdbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        rdbFemenino.setBackground(new java.awt.Color(195, 223, 234));
        buttonGroup1.add(rdbFemenino);
        rdbFemenino.setText("Femenino");
        jPanel1.add(rdbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("FECHA DE NACIMIENTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setText("DIRECCIÓN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtDireccion.setBackground(new java.awt.Color(204, 204, 255));
        txtDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDireccion.setBorder(null);
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 334, 24));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 334, 10));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel12.setText("TELEFONO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(204, 204, 255));
        txtTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefono.setBorder(null);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 141, 24));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 140, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setText("CONTACTO DE EMERGENCIA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        txtFechaN.setBackground(new java.awt.Color(204, 204, 255));
        txtFechaN.setBorder(null);
        jPanel1.add(txtFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 179, 24));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 180, -1));

        tablaPaciente.setBackground(new java.awt.Color(229, 244, 254));
        tablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_paciente", "Nombre completo del paciente", "Fecha de nacimiento", "Genero", "Dirección", "Telefono", "Contacto de emergencia"
            }
        ));
        tablaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPaciente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 730, 100));

        btnActualizar.setBackground(new java.awt.Color(89, 171, 253));
        btnActualizar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(89, 171, 253));
        btnRegresar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        btnRegresar.setText("SALIR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 90, -1));

        txtContacto.setBackground(new java.awt.Color(204, 204, 255));
        txtContacto.setBorder(null);
        jPanel1.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 179, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tablaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPacienteMouseClicked
        // TODO add your handling code here:
        int fila = tablaPaciente.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        } else {
            id_paciente = Integer.parseInt(tablaPaciente.getValueAt(fila, 0).toString());
            String nombre = tablaPaciente.getValueAt(fila, 1).toString();
            String fecha_nacimiento = tablaPaciente.getValueAt(fila, 2).toString();
            String genero = tablaPaciente.getValueAt(fila, 3).toString();
            String domicilio = tablaPaciente.getValueAt(fila, 4).toString();
            String telefono = tablaPaciente.getValueAt(fila, 5).toString();
            String contacto_emergencia = tablaPaciente.getValueAt(fila, 6).toString();
            
            //Configurar el nombre
            txtNombre.setText(nombre);
            
            //Configurar la fecha de nacimiento
            txtFechaN.setText(fecha_nacimiento);
            
            //Configurar el genero
            if ("M".equals(genero)) {
            rdbMasculino.setSelected(true);
            rdbFemenino.setSelected(false);
        } else {
            rdbMasculino.setSelected(false);
            rdbFemenino.setSelected(true);
        }
            
            //Configurar el domicilio
            txtDireccion.setText(domicilio);
            
            //Configurar el telefono
            txtTelefono.setText(telefono);
            
            //Configurar el contacto de emergencia
            txtContacto.setText(contacto_emergencia);
        }
    }//GEN-LAST:event_tablaPacienteMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    void actualizar(){
        int fila = tablaPaciente.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }
        else{           
            String nombre = txtNombre.getText();
            String fecha_nacimiento = txtFechaN.getText();
            String genero;
            if (rdbMasculino.isSelected()) {
        genero = "M";
    } else if (rdbFemenino.isSelected()) {
        genero = "F";
    } else {
        // Manejar el caso en el que no se seleccionó ninguno
        genero = "N";
    }
            String domicilio = txtDireccion.getText();
            String telefono = txtTelefono.getText();
            String contacto_emergencia = txtContacto.getText();
            
            // Crear un objeto paciente
            paciente p = new paciente();
            p.setId_paciente(id_paciente);
            p.setNombre(nombre);
            p.setFecha_nacimiento(fecha_nacimiento);
            p.setGenero(genero);
            p.setDomicilio(domicilio);
            p.setTelefono(telefono);
            p.setContacto_emergencia(contacto_emergencia);

            // Verificar si algún campo obligatorio está vacío
    if (camposVacios()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // No se realiza la inserción si hay campos vacíos
    }
    
            // Llamar al método actualizar de tu pacienteDAO
            int resultado = dao.actualizar(p);

            // Verificar si la actualización fue exitosa
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente");
                listar(); // Actualizar la tabla después de la actualización
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el registro");
            }
        }
        
        limpiar();
        
    }
    
    // Verificar si algún campo obligatorio está vacío
    boolean camposVacios() {
    return txtNombre.getText().isEmpty() || txtFechaN.getText().isEmpty() || txtDireccion.getText().isEmpty() || txtTelefono.getText().isEmpty();
}
    
    //Limpiar las cajas de texto
    void limpiar(){
        txtNombre.setText("");
        buttonGroup1.clearSelection();
        txtFechaN.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtContacto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JTable tablaPaciente;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaN;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
