
package VISTAS;

import MODELO.paciente;
import MODELO.tratamiento;
import MODELO.tratamientoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Darileysi Morales
 */
public class ActualizarTratamiento extends javax.swing.JInternalFrame {
    tratamientoDAO daot = new tratamientoDAO();;
    DefaultTableModel modelo = new DefaultTableModel();
    int id_tratamiento;
    int id_paciente;

    /**
     * Creates new form ActualizarTratamiento
     */
    public ActualizarTratamiento() {
        initComponents();
        listar();
        cmbPaciente.setSelectedIndex(-1);
        cmbTipo.setSelectedIndex(-1); 
    }

    void listar() {
    List<tratamiento> lista = daot.listar();
    modelo = (DefaultTableModel) tablaTratamiento.getModel();
    modelo.setRowCount(0); // Limpia la tabla antes de agregar nuevos datos
    // Limpiamos el ComboBox antes de agregar nuevos elementos
    cmbPaciente.removeAllItems();
    // Obtenemos la lista de pacientes
    List<String> listaPacientes = daot.listarPacientes();

    // Agregamos los nombres de los pacientes al ComboBox
    for (String nombrePaciente : listaPacientes) {
        cmbPaciente.addItem(nombrePaciente);
    }
    
    Object[] ob = new Object[9];
    
    for (int i = 0; i < lista.size(); i++) {
        ob[0] = lista.get(i).getId_tratamiento();
        ob[1] = lista.get(i).getId_paciente();
        ob[2] = lista.get(i).getFecha();
        ob[3] = lista.get(i).getTipo_diabetes();
        ob[4] = lista.get(i).getCondiciones_medicas();
        ob[5] = lista.get(i).getMedicamentos_dosis();
        ob[6] = lista.get(i).getNivel_glucosa();
        ob[7] = lista.get(i).getPeso();
        ob[8] = lista.get(i).getDescripcion_dieta();
        modelo.addRow(ob);
    }
    
    tablaTratamiento.setModel(modelo);
    System.out.println("Listado de tratamientos completado.");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbPaciente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCondiciones = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMedicamentos = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtGlucosa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDieta = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTratamiento = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(195, 223, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(195, 223, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE CONTROL DE PACIENTES CON DIABETES");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("ACTUALIZAR TRATAMIENTO");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Gobierno de Mexico.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Secretaria de salud.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/INSABI.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/GUERRERO.jpg"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Transformando GUERRERO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(208, 208, 208)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)))
                .addGap(105, 105, 105)
                .addComponent(jLabel15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(386, 386, 386))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 120));

        jPanel4.setBackground(new java.awt.Color(195, 223, 234));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("PACIENTE");

        cmbPaciente.setBackground(new java.awt.Color(204, 204, 255));
        cmbPaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbPaciente.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("FECHA DE REGISTRO");

        txtFecha.setBackground(new java.awt.Color(204, 204, 255));
        txtFecha.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("TIPO DE DIABETES");

        cmbTipo.setBackground(new java.awt.Color(204, 204, 255));
        cmbTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diabetes tipo I", "Diabetes tipo II" }));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("CONDICIONES MÉDICAS");

        txaCondiciones.setBackground(new java.awt.Color(204, 204, 255));
        txaCondiciones.setColumns(20);
        txaCondiciones.setRows(5);
        txaCondiciones.setBorder(null);
        jScrollPane1.setViewportView(txaCondiciones);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("MEDICAMENTOS Y DOSIS");

        txaMedicamentos.setBackground(new java.awt.Color(204, 204, 255));
        txaMedicamentos.setColumns(20);
        txaMedicamentos.setRows(5);
        jScrollPane2.setViewportView(txaMedicamentos);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setText("GLUCOSA");

        txtGlucosa.setBackground(new java.awt.Color(204, 204, 255));
        txtGlucosa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtGlucosa.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("PESO");

        txtPeso.setBackground(new java.awt.Color(204, 204, 255));
        txtPeso.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("DIETA");

        txaDieta.setBackground(new java.awt.Color(204, 204, 255));
        txaDieta.setColumns(20);
        txaDieta.setRows(5);
        jScrollPane3.setViewportView(txaDieta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtGlucosa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 21, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(252, 252, 252)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addGap(180, 180, 180)))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtGlucosa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 770, 390));

        btnActualizar.setBackground(new java.awt.Color(89, 171, 253));
        btnActualizar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 100, 24));

        btnSalir.setBackground(new java.awt.Color(89, 171, 253));
        btnSalir.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 100, 24));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tablaTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_Tratamiento", "Id_Paciente", "Fecha", "Tipo de diabetes", "Condiciones medicas", "Medicamentos", "Glucosa", "Peso", "Dieta"
            }
        ));
        tablaTratamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTratamientoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaTratamiento);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 1040, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaTratamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTratamientoMouseClicked
        // TODO add your handling code here:
        int fila = tablaTratamiento.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        } else {
            id_tratamiento = Integer.parseInt(tablaTratamiento.getValueAt(fila, 0).toString());         
            id_paciente = Integer.parseInt(tablaTratamiento.getValueAt(fila, 1).toString());
            String fecha = tablaTratamiento.getValueAt(fila, 2).toString();
            String tipo_diabetes = tablaTratamiento.getValueAt(fila, 3).toString();
            String condiciones_medicas = tablaTratamiento.getValueAt(fila, 4).toString();
            String medicamentos_dosis = tablaTratamiento.getValueAt(fila, 5).toString();
            String nivel_glucosa = tablaTratamiento.getValueAt(fila, 6).toString();
            Double peso = Double.parseDouble(tablaTratamiento.getValueAt(fila, 7).toString());
            String descripcion_dieta = tablaTratamiento.getValueAt(fila, 8).toString();
            
            //Configurar el id del paciente
            String nombrePaciente = daot.obtenerPacientePorId(id_paciente);
        if (nombrePaciente != null) {
            cmbPaciente.setSelectedItem(nombrePaciente);
        } else {
            // Manejar el caso en que no se encuentre el paciente
        }
            
            //Configurar la fecha de nacimiento
            txtFecha.setText(fecha);
            
            //Configurar el tipo de diabetes
            cmbTipo.setSelectedItem(tipo_diabetes);
            
            //Configurar las condiciones medicas
            txaCondiciones.setText(condiciones_medicas);
            
            //Configurar los medicamentos 
            txaMedicamentos.setText(medicamentos_dosis);
            
            //Configurar el nivel de glucosa
            txtGlucosa.setText(nivel_glucosa);
            
            //Configurar el peso
            txtPeso.setText(String.valueOf(peso));            

            //Configurar la descripcion de la dieta
            txaDieta.setText(descripcion_dieta);
        }
        
    }//GEN-LAST:event_tablaTratamientoMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

 void actualizar(){
        int fila = tablaTratamiento.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }
        else{           
            //Obtener el nombre y despues el id
            String nombrePaciente = (String) cmbPaciente.getSelectedItem();
            int id_paciente = daot.obtenerIdPacientePorNombre(nombrePaciente);
            
            String fecha = txtFecha.getText();
            String tipo_diabetes = (String) cmbTipo.getSelectedItem();
            String condiciones_medicas = txaCondiciones.getText();
            String medicamentos_dosis = txaMedicamentos.getText();
            String nivel_glucosa = txtGlucosa.getText();
            Double peso = Double.parseDouble(txtPeso.getText());
            String descripcion_dieta = txaDieta.getText();
            
            // Crear un objeto tratamiento
            tratamiento t = new tratamiento();
            t.setId_tratamiento(id_tratamiento);
            t.setId_paciente(id_paciente);
            t.setFecha(fecha);
            t.setTipo_diabetes(tipo_diabetes);
            t.setCondiciones_medicas(condiciones_medicas);
            t.setMedicamentos_dosis(medicamentos_dosis);
            t.setNivel_glucosa(nivel_glucosa);
            t.setPeso(peso);
            t.setDescripcion_dieta(descripcion_dieta);

            // Verificar si algún campo obligatorio está vacío
    if (camposVacios()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // No se realiza la inserción si hay campos vacíos
    }
    
            // Llamar al método actualizar de tratamientoDAO
            int resultado = daot.actualizar(t);

            // Verificar si la actualización fue exitosa
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente");
                listar(); // Actualizar la tabla después de la actualización
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el registro");
            }
        }
        
        limpiar();
        
    }
    
    // Verificar si algún campo obligatorio está vacío
    boolean camposVacios() {
    return txtFecha.getText().isEmpty() || txtGlucosa.getText().isEmpty() || txtPeso.getText().isEmpty() || 
            txaCondiciones.getText().isEmpty() || txaMedicamentos.getText().isEmpty() || txaDieta.getText().isEmpty();
}
    
    //Limpiar las cajas de texto
    void limpiar(){
        txtFecha.setText("");
        txtGlucosa.setText("");
        txtPeso.setText("");
        txaCondiciones.setText("");
        txaMedicamentos.setText("");
        txaDieta.setText("");
        cmbPaciente.setSelectedIndex(-1);
        cmbTipo.setSelectedIndex(-1); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbPaciente;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaTratamiento;
    private javax.swing.JTextArea txaCondiciones;
    private javax.swing.JTextArea txaDieta;
    private javax.swing.JTextArea txaMedicamentos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGlucosa;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
