
package VISTAS;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
/**
 *
 * @author Darileysi Morales
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setContentPane(VentanaPrincipal);  
        this.setLocationRelativeTo(null); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Paciente = new javax.swing.JMenu();
        MenuPacientes = new javax.swing.JMenuItem();
        menuActualizarP = new javax.swing.JMenuItem();
        MenuT = new javax.swing.JMenu();
        menuTratamiento = new javax.swing.JMenuItem();
        menuActualizarT = new javax.swing.JMenuItem();
        MenuCitas = new javax.swing.JMenu();
        menuCita = new javax.swing.JMenuItem();
        MenuHistorial = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuCerrar = new javax.swing.JMenu();
        menuCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VentanaPrincipal.setBackground(new java.awt.Color(195, 198, 255));
        VentanaPrincipal.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 30));

        Paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paciente.png"))); // NOI18N
        Paciente.setText("PACIENTES");

        MenuPacientes.setText("Registrar pacientes");
        MenuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPacientesActionPerformed(evt);
            }
        });
        Paciente.add(MenuPacientes);

        menuActualizarP.setText("Actualizar registro de pacientes");
        menuActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarPActionPerformed(evt);
            }
        });
        Paciente.add(menuActualizarP);

        jMenuBar1.add(Paciente);

        MenuT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/doctor.png"))); // NOI18N
        MenuT.setText("TRATAMIENTOS");

        menuTratamiento.setText("Registrar tratamientos");
        menuTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTratamientoActionPerformed(evt);
            }
        });
        MenuT.add(menuTratamiento);

        menuActualizarT.setText("Actualizar tratamientos");
        menuActualizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarTActionPerformed(evt);
            }
        });
        MenuT.add(menuActualizarT);

        jMenuBar1.add(MenuT);

        MenuCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cita-medica.png"))); // NOI18N
        MenuCitas.setText("CITAS MÉDICAS");

        menuCita.setText("Gestión de citas");
        menuCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCitaActionPerformed(evt);
            }
        });
        MenuCitas.add(menuCita);

        jMenuBar1.add(MenuCitas);

        MenuHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paciente.png"))); // NOI18N
        MenuHistorial.setText("HISTORIAL MÉDICO");
        MenuHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHistorialActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Historial medico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuHistorial.add(jMenuItem1);

        jMenuBar1.add(MenuHistorial);

        MenuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cerrar-sesion.png"))); // NOI18N
        MenuCerrar.setText("CERRAR SESIÓN");

        menuCerrar.setText("Cerrar sesión");
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        MenuCerrar.add(menuCerrar);

        jMenuBar1.add(MenuCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void MenuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPacientesActionPerformed
        RegistroPacientes paciente = new RegistroPacientes();
        paciente.setVisible(true);
        CentrarVentana(paciente);
    }//GEN-LAST:event_MenuPacientesActionPerformed

    private void menuActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarPActionPerformed
        ActualizarPacientes actualizar = new ActualizarPacientes();
        actualizar.setVisible(true);
        CentrarVentana(actualizar);
    }//GEN-LAST:event_menuActualizarPActionPerformed

    private void menuTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTratamientoActionPerformed
        RegistrarTratamiento tratamiento = new RegistrarTratamiento();
        tratamiento.setVisible(true);
        CentrarVentana(tratamiento);
    }//GEN-LAST:event_menuTratamientoActionPerformed

    private void menuActualizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarTActionPerformed
        ActualizarTratamiento actualizarT = new ActualizarTratamiento();
        actualizarT.setVisible(true);
        CentrarVentana(actualizarT);
    }//GEN-LAST:event_menuActualizarTActionPerformed

    private void menuCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCitaActionPerformed
        // TODO add your handling code here:
        GestionCitas gestionC = new GestionCitas();
        gestionC.setVisible(true);
        CentrarVentana(gestionC);
    }//GEN-LAST:event_menuCitaActionPerformed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }//GEN-LAST:event_menuCerrarActionPerformed

    private void MenuHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHistorialActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuHistorialActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        HistorialClinico historial = new HistorialClinico();
        historial.setVisible(true);
        CentrarVentana(historial);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    void CentrarVentana(JInternalFrame frame) {
    VentanaPrincipal.add(frame);

    Dimension desktopSize = VentanaPrincipal.getSize();
    Dimension frameSize = frame.getSize();

    // Asegurarse de que la ventana interna no sea más grande que el escritorio
    frameSize.width = Math.min(frameSize.width, desktopSize.width);
    frameSize.height = Math.min(frameSize.height, desktopSize.height);

    // Calcular las coordenadas para centrar la ventana interna
    int x = (desktopSize.width - frameSize.width) / 2;
    int y = (desktopSize.height - frameSize.height) / 2;

    // Establecer la posición de la ventana interna
    frame.setLocation(x, y);

    // Hacer visible la ventana interna
    frame.setVisible(true);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCerrar;
    private javax.swing.JMenu MenuCitas;
    private javax.swing.JMenu MenuHistorial;
    private javax.swing.JMenuItem MenuPacientes;
    private javax.swing.JMenu MenuT;
    private javax.swing.JMenu Paciente;
    private javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuActualizarP;
    private javax.swing.JMenuItem menuActualizarT;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JMenuItem menuCita;
    private javax.swing.JMenuItem menuTratamiento;
    // End of variables declaration//GEN-END:variables
}
